version: '3.3'
services:
  dev-db:
    image: postgres:13
    ports:
      - 5434:5432
    env_file:
      - docker.env
    networks:
      - freecodecamp
  test-db:
    image: postgres:13
    ports:
      - 5435:5432
    env_file:
      - docker.env
    networks:
      - freecodecamp
networks:
  freecodecamp:
