version: '3.3'
services:
  dev-db:
    image: postgres:13
    ports:
      - 5434:5432
    env_file:
      - .env
    environment:
      POSTGRES_USER: '${POSTGRES_USER}'
      POSTGRES_PASSWORD: '${POSTGRES_PASS}'
      POSTGRES_DB: '${POSTGRES_NAME}'
    networks:
      - freecodecamp
  test-db:
    image: postgres:13
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: '${POSTGRES_USER}'
      POSTGRES_PASSWORD: '${POSTGRES_PASS}'
      POSTGRES_DB: '${POSTGRES_NAME}'
    networks:
      - freecodecamp
networks:
  freecodecamp:
